version: '3.8'

services:
# Servicio para la base de datos
  crud-db:
    image: postgres:13
    container_name: crud-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=cruddb
    networks:
      - crud-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cruddb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

# Servicio para el backend (Spring Boot)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiendatextil
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://crud-db:5432/cruddb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - crud-network
    ports:
      - "8080:8080"
    depends_on:
      crud-db:
        condition: service_healthy
    env_file:
      - .env

# Servicio para el frontend (Quasar)
  front:
    build:
      context: ./quasar-project
      dockerfile: Dockerfile
    container_name: quasar-app
    ports:
      - "8081:8081"
    environment:
      - VUE_APP_API_URL=http://localhost:8080/api
    networks:
      - crud-network
    volumes:
      - ./quasar-project:/app  
      - /app/node_modules 
    command: ["quasar", "dev", "--hostname", "0.0.0.0", "--port", "8081"] 

networks:
  crud-network:
    driver: bridge

volumes:
  postgres_data: