version: '3.8'
services:
  db:
    image: postgres:13
    container_name: crud-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    networks:
      - crud-network
  app:
    image: crud-spring-app
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - crud-network
    restart: always

networks:
  crud-network:
    driver: bridge
